### ISSUE TITLE
Invalid JSON when query result is empty or especial characters

### ISSUE THREAD

**Issue by lbuse** [rabrux/dbf-proxy#1]
Hi @rabrux! I'm using your[ node-dbf-proxy](https://github.com/rabrux/node-dbf-proxy) in one of my projects and I'm facing two issues that I believe are related to the dbf-proxy project. Just to clarify, I don't know c#, and I'm hoping you are able to helpe me.

**1st** problem is related to an empty result, I believe that an blank string is returning, something like this **"  "**, and this [line](https://github.com/rabrux/dbf-proxy/blob/48a79903f43788805947fb3ac7817f0fe9841c49/dbf/Program.cs#L77) shows the `JSONString.Append("[")` bein appended only if there is a result.

**2nd** problem is releated to values that might have double quotes, or any other character that belongs to the json structure I think.

This two projects are really handy, thank you for making them available.

**Comment by lbuse** [comment]
I'm closing the issue, I'm trying another approach and this package is no longer needed. Thanks anyway!

**Comment by rabrux** [comment]
Hi @lucasbusellato sorry if I reply at this time, I must confess that I am not a c# coder at all, this project was made to connect a Visual FoxPro in it's version 5 to a REST API, it reads and writes to dbf files but only in version 9, because of this, we decide not to continue with this approach.

The issue that you had is everything that you describe it, by the moment I do not have access to a Windows environment to try to fix this error, all the ecosystem required by the project itself its on my old job.

I try to check it maybe it works on a virtual machine.

Sorry for the English.

Saludos.

**Comment by lbuse** [comment]
Hello @rabrux! Don't worry English is not my first language too.
Funny enough, I'm in a similar situation where I need to build this bridge with node to make this dbf accessible. Your project was a really good starting point.

Well, after trying other options I forked your project, and changed to solve these problems and now I'm using in the my project.

Right now I can't release this changes as a dbf-proxy2 because I'm focusing on this project I'm doing.

If you want to see the changes I've made, you can check here: https://github.com/lucasbusellato/dbf-proxy

Here is a list of the critical ones:
1. Target framework changed to 4.7.2
2. Signing certificate is disabled now
3. Console output is set to utf8 (because I was having problems with encoding)
4. The function responsible for building the json, now uses Json.NET.
5. Added a simple checking to guess if the SQL command is a "select" to return data or is something like an "update" where I need to know how many rows where affected.
